// Fallback data based on the real NailIt API response structure from the attached file
// This contains a sample of the actual 398 services available in the NailIt system

export const nailItFallbackItems = [
  {
    "Item_Id": 51364,
    "Item_Name": "Hair Growth Helmet Treatment",
    "Item_Desc": "Its a hair growth therapy<br />\r\n<br />\r\nBenefits<br />\r\n-&nbsp;Treatment of Hair Loss &amp; Hair Thinning<br />\r\n-&nbsp;Balance Scalp oil secretion<br />\r\n-&nbsp;Improves Hair quality<br />\r\n-&nbsp;Improves Blood Circulation<br />\r\n<br />\r\n<span style=\"font-size: 13.3333px;\">Safe, Pain Free, Not recommended for pregnant, For adults only</span>",
    "Image_Url": "Uploads/ProductImage/f253ec6a6faf_1.jpg",
    "Primary_Price": 5.000,
    "Dis_Percent": 0.0,
    "Dis_Amount": 0.0,
    "Special_Price": 5.000,
    "Is_Favorite": false,
    "Promotion_Id": 0,
    "Promotion_Type_Id": 0,
    "Item_Type_Id": 2,
    "Available_Qty": 0,
    "Duration": "30",
    "Parent_Group_Id": 7,
    "Sub_Group_Id": 2120,
    "Event_Type": 1,
    "Is_Gift": false,
    "Location_Ids": [1, 52, 53, 57],
    "Media": [],
    "Sizes": []
  },
  {
    "Item_Id": 4,
    "Item_Name": "Hair Wash",
    "Item_Desc": "Hair Wash",
    "Image_Url": "Uploads/ProductImage/ea09232def8c_Hair Wash.jpg",
    "Primary_Price": 2.000,
    "Dis_Percent": 0.0,
    "Dis_Amount": 0.0,
    "Special_Price": 2.000,
    "Is_Favorite": false,
    "Promotion_Id": 0,
    "Promotion_Type_Id": 0,
    "Item_Type_Id": 2,
    "Available_Qty": 0,
    "Duration": "30",
    "Parent_Group_Id": 7,
    "Sub_Group_Id": 2097,
    "Event_Type": 1,
    "Is_Gift": false,
    "Location_Ids": [1, 52, 53, 60],
    "Media": [],
    "Sizes": []
  },
  {
    "Item_Id": 5,
    "Item_Name": "Macadamia Hair Treatment",
    "Item_Desc": "<span style=\"font-size: 13.3333px;\">A treatment that exclusively for dry, damaged &amp; color treated hair of all textures, it contains a blend of omega-rich &amp; argan oils to smooth frizz and retain moisture that add shine to the hair.</span>",
    "Image_Url": "Uploads/ProductImage/3cb92dbf7327_macademia.jpg",
    "Primary_Price": 10.000,
    "Dis_Percent": 0.0,
    "Dis_Amount": 0.0,
    "Special_Price": 10.000,
    "Is_Favorite": false,
    "Promotion_Id": 0,
    "Promotion_Type_Id": 0,
    "Item_Type_Id": 2,
    "Available_Qty": 0,
    "Duration": "60",
    "Parent_Group_Id": 7,
    "Sub_Group_Id": 2120,
    "Event_Type": 1,
    "Is_Gift": false,
    "Location_Ids": [1, 52, 53, 60],
    "Media": [],
    "Sizes": [
      {
        "Size_Id": 10349,
        "Size_Name": "Boy Hair",
        "Price": 7.000,
        "Available_Qty": 0
      },
      {
        "Size_Id": 10350,
        "Size_Name": "Short Hair",
        "Price": 8.000,
        "Available_Qty": 0
      },
      {
        "Size_Id": 10351,
        "Size_Name": "Medium Hair",
        "Price": 9.000,
        "Available_Qty": 0
      },
      {
        "Size_Id": 10352,
        "Size_Name": "Long Hair",
        "Price": 10.000,
        "Available_Qty": 0
      }
    ]
  },
  {
    "Item_Id": 60,
    "Item_Name": "Olaplex with Hair Color Treatment",
    "Item_Desc": "A treatment that reconnects the broken bonds &amp; repair the damage to the hair that has been compromised by chemical processing, heat styling. It maintains the hair strenght.",
    "Image_Url": "Uploads/ProductImage/7fd04170cca5_Olaplex.jpg",
    "Primary_Price": 30.000,
    "Dis_Percent": 0.0,
    "Dis_Amount": 0.0,
    "Special_Price": 30.000,
    "Is_Favorite": false,
    "Promotion_Id": 0,
    "Promotion_Type_Id": 0,
    "Item_Type_Id": 2,
    "Available_Qty": 0,
    "Duration": "60",
    "Parent_Group_Id": 7,
    "Sub_Group_Id": 2120,
    "Event_Type": 1,
    "Is_Gift": false,
    "Location_Ids": [1, 52, 53, 60],
    "Media": [],
    "Sizes": [
      {
        "Size_Id": 10491,
        "Size_Name": "Boy Hair",
        "Price": 15.000,
        "Available_Qty": 0
      },
      {
        "Size_Id": 10492,
        "Size_Name": "Short Hair",
        "Price": 20.000,
        "Available_Qty": 0
      },
      {
        "Size_Id": 10493,
        "Size_Name": "Medium Hair",
        "Price": 25.000,
        "Available_Qty": 0
      },
      {
        "Size_Id": 10494,
        "Size_Name": "Long  Hair",
        "Price": 30.000,
        "Available_Qty": 0
      }
    ]
  },
  {
    "Item_Id": 61,
    "Item_Name": "Olaplex Hair Treatment",
    "Item_Desc": "A treatment that reconnects the broken bonds &amp; repair the damage to the hair that has been compromised by chemical processing, heat styling. It maintains the hair strenght. Mix with color to prevent damage and with a root touch up to protect delecates strands while lightening.",
    "Image_Url": "Uploads/ProductImage/6f8099ec4a14_Olaplex.jpg",
    "Primary_Price": 15.000,
    "Dis_Percent": 0.0,
    "Dis_Amount": 0.0,
    "Special_Price": 15.000,
    "Is_Favorite": false,
    "Promotion_Id": 0,
    "Promotion_Type_Id": 0,
    "Item_Type_Id": 2,
    "Available_Qty": 0,
    "Duration": "60",
    "Parent_Group_Id": 7,
    "Sub_Group_Id": 2120,
    "Event_Type": 1,
    "Is_Gift": false,
    "Location_Ids": [1, 52, 53, 60],
    "Media": [],
    "Sizes": []
  },
  {
    "Item_Id": 64,
    "Item_Name": "Tea Tree Hair Treatment",
    "Item_Desc": "A treatment the unclog hair follicles, an invigorating &amp; soothing &amp; calming treatment. Good for hair &amp; scalp issues need immediate intervention that help with tingly dose of straightening &amp; condition the hair with skin refining agents.",
    "Image_Url": "Uploads/ProductImage/146f13b04a5e_tea tree.jpg",
    "Primary_Price": 12.000,
    "Dis_Percent": 0.0,
    "Dis_Amount": 0.0,
    "Special_Price": 12.000,
    "Is_Favorite": false,
    "Promotion_Id": 0,
    "Promotion_Type_Id": 0,
    "Item_Type_Id": 2,
    "Available_Qty": 0,
    "Duration": "30",
    "Parent_Group_Id": 7,
    "Sub_Group_Id": 2120,
    "Event_Type": 1,
    "Is_Gift": false,
    "Location_Ids": [1, 52, 53, 60],
    "Media": [],
    "Sizes": [
      {
        "Size_Id": 10361,
        "Size_Name": "Boy Hair",
        "Price": 8.000,
        "Available_Qty": 0
      },
      {
        "Size_Id": 10362,
        "Size_Name": "Short Hair",
        "Price": 9.000,
        "Available_Qty": 0
      },
      {
        "Size_Id": 10363,
        "Size_Name": "Medium Hair",
        "Price": 10.000,
        "Available_Qty": 0
      },
      {
        "Size_Id": 10364,
        "Size_Name": "Long Hair",
        "Price": 12.000,
        "Available_Qty": 0
      }
    ]
  },
  {
    "Item_Id": 85,
    "Item_Name": "Ginger Scalp Scrub Treatment",
    "Item_Desc": "it helps stimulates hair folicles with turn promotes hair growth, it straightening your hair strands to combat hair loss, and it contributes to restroring noisture loss.",
    "Image_Url": "Uploads/ProductImage/ac4d49422ff2_Ginger.jpg",
    "Primary_Price": 5.000,
    "Dis_Percent": 0.0,
    "Dis_Amount": 0.0,
    "Special_Price": 5.000,
    "Is_Favorite": false,
    "Promotion_Id": 0,
    "Promotion_Type_Id": 0,
    "Item_Type_Id": 2,
    "Available_Qty": 0,
    "Duration": "30",
    "Parent_Group_Id": 7,
    "Sub_Group_Id": 2097,
    "Event_Type": 1,
    "Is_Gift": false,
    "Location_Ids": [1, 52, 53, 60],
    "Media": [],
    "Sizes": []
  },
  {
    "Item_Id": 72,
    "Item_Name": "Pumpkin Treatment",
    "Item_Desc": "a treatment that good for dry and damaged hair. Keeping the hair healthy and re-growth&nbsp;",
    "Image_Url": "Uploads/ProductImage/fdc0d21a1a9d_Pumpkin.jpg",
    "Primary_Price": 5.000,
    "Dis_Percent": 0.0,
    "Dis_Amount": 0.0,
    "Special_Price": 5.000,
    "Is_Favorite": false,
    "Promotion_Id": 0,
    "Promotion_Type_Id": 0,
    "Item_Type_Id": 2,
    "Available_Qty": 0,
    "Duration": "30",
    "Parent_Group_Id": 7,
    "Sub_Group_Id": 2097,
    "Event_Type": 1,
    "Is_Gift": false,
    "Location_Ids": [1, 52, 53, 60],
    "Media": [],
    "Sizes": []
  },
  {
    "Item_Id": 73,
    "Item_Name": "Banana Treatment",
    "Item_Desc": "A treatment that is good for hair and scalp, it improves manageability and shine, it prevent and control dandruff and it moisturize the scalp. It prevents split ends and breakage.",
    "Image_Url": "Uploads/ProductImage/3d7a303bdd1f_Banana.jpg",
    "Primary_Price": 5.000,
    "Dis_Percent": 0.0,
    "Dis_Amount": 0.0,
    "Special_Price": 5.000,
    "Is_Favorite": false,
    "Promotion_Id": 0,
    "Promotion_Type_Id": 0,
    "Item_Type_Id": 2,
    "Available_Qty": 0,
    "Duration": "30",
    "Parent_Group_Id": 7,
    "Sub_Group_Id": 2097,
    "Event_Type": 1,
    "Is_Gift": false,
    "Location_Ids": [1, 52, 53],
    "Media": [],
    "Sizes": []
  },
  {
    "Item_Id": 74,
    "Item_Name": "Avocado Treatment",
    "Item_Desc": "A treatment that helps rejuvinate and moisturize the scalp. Rich with protein and vitamins. It helps soothe the scalp and promote long, strong healthy hair growth.&nbsp;",
    "Image_Url": "Uploads/ProductImage/643a3a859c4c_Avocado.jpg",
    "Primary_Price": 5.000,
    "Dis_Percent": 0.0,
    "Dis_Amount": 0.0,
    "Special_Price": 5.000,
    "Is_Favorite": false,
    "Promotion_Id": 0,
    "Promotion_Type_Id": 0,
    "Item_Type_Id": 2,
    "Available_Qty": 0,
    "Duration": "30",
    "Parent_Group_Id": 7,
    "Sub_Group_Id": 2097,
    "Event_Type": 1,
    "Is_Gift": false,
    "Location_Ids": [1, 52, 53, 60],
    "Media": [],
    "Sizes": []
  }
];

// Location mapping based on known NailIt locations
export const locationMapping = {
  1: "Al-Plaza Mall",
  52: "Zahra Complex", 
  53: "Arraya Mall",
  57: "Al-Kout Mall",
  60: "Marina Mall"
};